# Generated by Django 3.0.2 on 2020-01-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
